export const ADD_COUNTER = 'add_counter'
export const CUT_COUNTER = 'cut_counter'
export const ADD_TO_CAR = 'add_to_car'
export const CLEAR_CAR = 'clear_car'
export const CLEAR_CAR_ITEM = 'clear_car_item'
export const CHECKED_CHANGE = 'checked_change'